"""
ml/reports/pdf_generator.py — Professional PDF Report (Card Layout)
Each violation = a standalone card with:
  Left column:  ID, Type, Layer, Rule, Severity, Standard
  Right column: Description bullets + Suggestion bullets
No text overflow possible — 2 wide columns = 87mm each.
"""

import io
import json
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, HRFlowable, KeepTogether,
    NextPageTemplate, PageBreak, PageTemplate,
    Paragraph, Spacer, Table, TableStyle
)

# ── Palette ────────────────────────────────────────────────────────────────────
VARROC_BLUE   = colors.HexColor('#003366')
VARROC_ORANGE = colors.HexColor('#E87722')
COL_CRITICAL  = colors.HexColor('#922B21')
COL_MAJOR     = colors.HexColor('#A04000')
COL_MINOR     = colors.HexColor('#1D6A39')
FILL_CRIT_HDR = colors.HexColor('#E8DADB')
FILL_MAJOR_HDR= colors.HexColor('#FAE5D3')
FILL_MINOR_HDR= colors.HexColor('#D5F5E3')
FILL_CRIT_BG  = colors.HexColor('#FEF5F5')
FILL_MAJOR_BG = colors.HexColor('#FFF9F5')
FILL_MINOR_BG = colors.HexColor('#F9FEF9')
FILL_HDR_TBL  = colors.HexColor('#1B4F72')
FILL_ALT      = colors.HexColor('#F2F6FC')
WHITE         = colors.white
DARK          = colors.HexColor('#1C2833')
GREY          = colors.HexColor('#626567')

FOOTER = "Generated by VARROC AI Validation System  |  Not a substitute for qualified engineering review"
PW, PH = A4
CONTENT_W = PW - 36*mm   # 174mm


# ── Styles ─────────────────────────────────────────────────────────────────────
def S():
    return {
        'cover_h1': ParagraphStyle('cover_h1',
            fontName='Helvetica-Bold', fontSize=26, textColor=WHITE,
            alignment=TA_CENTER, spaceAfter=4),
        'cover_sub': ParagraphStyle('cover_sub',
            fontName='Helvetica', fontSize=12,
            textColor=colors.HexColor('#BDC3C7'),
            alignment=TA_CENTER, spaceAfter=3),
        'section': ParagraphStyle('section',
            fontName='Helvetica-Bold', fontSize=16,
            textColor=VARROC_BLUE, spaceBefore=12, spaceAfter=3),
        'card_meta_label': ParagraphStyle('card_meta_label',
            fontName='Helvetica-Bold', fontSize=8,
            textColor=GREY, leading=11),
        'card_meta_val': ParagraphStyle('card_meta_val',
            fontName='Helvetica', fontSize=9,
            textColor=DARK, leading=12),
        'card_sev_critical': ParagraphStyle('card_sev_crit',
            fontName='Helvetica-Bold', fontSize=10,
            textColor=COL_CRITICAL, leading=12),
        'card_sev_major': ParagraphStyle('card_sev_major',
            fontName='Helvetica-Bold', fontSize=10,
            textColor=COL_MAJOR, leading=12),
        'card_sev_minor': ParagraphStyle('card_sev_minor',
            fontName='Helvetica-Bold', fontSize=10,
            textColor=COL_MINOR, leading=12),
        'bullet_label': ParagraphStyle('bullet_label',
            fontName='Helvetica-Bold', fontSize=8,
            textColor=DARK, leading=12, spaceAfter=2),
        'bullet': ParagraphStyle('bullet',
            fontName='Helvetica', fontSize=8,
            textColor=DARK, leading=12, leftIndent=10, spaceAfter=6),
        'small': ParagraphStyle('small',
            fontName='Helvetica', fontSize=7.5,
            textColor=GREY, leading=10),
        'small_bold': ParagraphStyle('small_bold',
            fontName='Helvetica-Bold', fontSize=7.5,
            textColor=GREY, leading=10),
        'summary_val': ParagraphStyle('summary_val',
            fontName='Helvetica', fontSize=9,
            textColor=DARK, leading=12),
        'summary_key': ParagraphStyle('summary_key',
            fontName='Helvetica-Bold', fontSize=9,
            textColor=DARK, leading=12),
        'footer': ParagraphStyle('footer',
            fontName='Helvetica-Oblique', fontSize=6.5,
            textColor=GREY, alignment=TA_CENTER),
    }


# ── Page templates ─────────────────────────────────────────────────────────────
class VarrocDoc(BaseDocTemplate):
    def __init__(self, buf, meta):
        super().__init__(buf, pagesize=A4,
                         leftMargin=18*mm, rightMargin=18*mm,
                         topMargin=14*mm, bottomMargin=20*mm)
        self.meta = meta
        self.addPageTemplates([
            PageTemplate(id='Cover', frames=[
                Frame(18*mm, 20*mm, CONTENT_W, PH - 34*mm)],
                onPage=self._cover_bg),
            PageTemplate(id='Body', frames=[
                Frame(18*mm, 20*mm, CONTENT_W, PH - 30*mm)],
                onPage=self._body_hdr),
        ])

    def _cover_bg(self, c, doc):
        c.saveState()
        c.setFillColor(VARROC_BLUE)
        c.rect(0, 0, PW, PH, fill=1, stroke=0)
        c.setFillColor(VARROC_ORANGE)
        c.rect(0, PH * 0.41, PW, 3, fill=1, stroke=0)
        c.rect(0, PH * 0.41 - 7, PW, 3, fill=1, stroke=0)
        c.setFont('Helvetica-Oblique', 6.5)
        c.setFillColor(colors.HexColor('#95A5A6'))
        c.drawCentredString(PW / 2, 12 * mm, FOOTER)
        c.restoreState()

    def _body_hdr(self, c, doc):
        # Minimal clean header — Fix 6
        c.saveState()
        c.setFillColor(VARROC_BLUE)
        c.rect(0, PH - 10*mm, PW, 10*mm, fill=1, stroke=0)
        c.setFillColor(VARROC_ORANGE)
        c.rect(0, PH - 11*mm, PW, 1*mm, fill=1, stroke=0)

        c.setFillColor(WHITE)
        c.setFont('Helvetica-Bold', 9)
        c.drawString(18*mm, PH - 6.5*mm, "VARROC AI VALIDATION SYSTEM")
        c.setFont('Helvetica', 8)
        did  = self.meta.get('drawingId', '—')
        eng  = self.meta.get('engineer', 'Varroc Engineer')
        date = str(self.meta.get('scanDate', ''))[:10]
        c.drawRightString(PW - 18*mm, PH - 6.5*mm,
            f"{did}  |  {eng}  |  {date}  |  p.{doc.page}")

        # Footer
        c.setStrokeColor(VARROC_ORANGE)
        c.setLineWidth(0.4)
        c.line(18*mm, 17*mm, PW - 18*mm, 17*mm)
        c.setFont('Helvetica-Oblique', 6.5)
        c.setFillColor(GREY)
        c.drawCentredString(PW / 2, 12*mm, FOOTER)
        c.restoreState()


# ── Helpers ────────────────────────────────────────────────────────────────────
def trunc(text, n=100):
    t = str(text or '').strip()
    return (t[:n] + '...') if len(t) > n else t


def to_bullets(text, max_chars=90, max_bullets=3):
    """Split text into bullet lines."""
    text = str(text or '').strip()
    if not text or text in ('None', '—', '(pending)'):
        return ['No data available']
    # split on '. ' or '\n'
    parts = []
    for seg in text.replace('. ', '.|').replace('\n', '.|').split('.|'):
        seg = seg.strip().rstrip('.')
        if seg:
            parts.append(trunc(seg, max_chars))
    return parts[:max_bullets] if parts else [trunc(text, max_chars)]


def sev_bg(sev):
    return {
        'Critical': (FILL_CRIT_HDR, FILL_CRIT_BG, COL_CRITICAL),
        'Major':    (FILL_MAJOR_HDR, FILL_MAJOR_BG, COL_MAJOR),
        'Minor':    (FILL_MINOR_HDR, FILL_MINOR_BG, COL_MINOR),
    }.get(sev, (FILL_ALT, WHITE, DARK))


def sev_sty(sev, sty):
    return {
        'Critical': sty['card_sev_critical'],
        'Major':    sty['card_sev_major'],
        'Minor':    sty['card_sev_minor'],
    }.get(sev, sty['summary_val'])


# ── Cover page ─────────────────────────────────────────────────────────────────
def cover(data, sty):
    counts  = data.get('counts', {})
    blocked = data.get('blocksSignOff', False)
    story   = [Spacer(1, 50*mm)]
    story  += [
        Paragraph("VARROC AI VALIDATION SYSTEM", sty['cover_h1']),
        Paragraph("Drawing Quality &amp; Compliance Report", sty['cover_sub']),
        Spacer(1, 7*mm),
        HRFlowable(width="70%", thickness=2, color=VARROC_ORANGE, hAlign='CENTER'),
        Spacer(1, 7*mm),
    ]
    meta = [
        ["Drawing ID",  data.get('drawingId','—')],
        ["Date",        str(data.get('scanDate',''))[:16]],
        ["Engineer",    data.get('engineer','Varroc Design Engineer')],
        ["Standards",   ", ".join(data.get('standardsChecked', []))],
        ["Violations",  str(counts.get('total', 0))],
        ["Critical",    str(counts.get('critical', 0))],
        ["Sign-Off",    "BLOCKED" if blocked else "CLEARED"],
    ]
    t = Table(meta, colWidths=[45*mm, 110*mm])
    t.setStyle(TableStyle([
        ('FONTNAME',     (0,0),(0,-1), 'Helvetica-Bold'),
        ('FONTNAME',     (1,0),(1,-1), 'Helvetica'),
        ('FONTSIZE',     (0,0),(-1,-1), 10),
        ('TEXTCOLOR',    (0,0),(-1,-1), WHITE),
        ('ROWBACKGROUND',(0,0),(-1,-1),
            [colors.HexColor('#1A3A5C'), colors.HexColor('#1F4E79')]),
        ('TOPPADDING',   (0,0),(-1,-1), 6),
        ('BOTTOMPADDING',(0,0),(-1,-1), 6),
        ('LEFTPADDING',  (0,0),(-1,-1), 10),
        ('GRID',         (0,0),(-1,-1), 0.3, colors.HexColor('#2E86C1')),
        ('TEXTCOLOR',    (1,6),(1,6),
            colors.HexColor('#E74C3C') if blocked else colors.HexColor('#27AE60')),
        ('FONTNAME',     (1,6),(1,6), 'Helvetica-Bold'),
    ]))
    story.append(t)
    story.append(NextPageTemplate('Body'))
    story.append(PageBreak())
    return story


# ── Executive Summary ──────────────────────────────────────────────────────────
def exec_summary(data, sty):
    counts  = data.get('counts', {})
    blocked = data.get('blocksSignOff', False)
    story   = [
        Paragraph("Executive Summary", sty['section']),
        HRFlowable(width="100%", thickness=0.6, color=VARROC_BLUE),
        Spacer(1, 4*mm),
    ]
    rows = [
        ["Metric", "Value", "Note"],
        ["Total Violations",   str(counts.get('total',0)), ""],
        ["Critical Issues",    str(counts.get('critical',0)),
             "Blocks sign-off" if counts.get('critical',0) else "None"],
        ["Major Issues",       str(counts.get('major',0)),
             "Review required" if counts.get('major',0) else "None"],
        ["Minor Issues",       str(counts.get('minorSuppressed',0)), "Best practice only"],
        ["Standards Checked",  ", ".join(data.get('standardsChecked',[])), ""],
        ["Sign-Off Decision",
             "BLOCKED — cannot release" if blocked else "CLEARED — ready for release", ""],
    ]
    t = Table(rows, colWidths=[55*mm, 72*mm, 47*mm])
    ts = TableStyle([
        ('BACKGROUND',   (0,0),(-1,0), FILL_HDR_TBL),
        ('TEXTCOLOR',    (0,0),(-1,0), WHITE),
        ('FONTNAME',     (0,0),(-1,0), 'Helvetica-Bold'),
        ('FONTNAME',     (0,1),(0,-1), 'Helvetica-Bold'),
        ('FONTSIZE',     (0,0),(-1,-1), 9),
        ('ROWBACKGROUND',(0,1),(-1,-1), [WHITE, FILL_ALT]),
        ('GRID',         (0,0),(-1,-1), 0.3, colors.HexColor('#BFC9CA')),
        ('TOPPADDING',   (0,0),(-1,-1), 6),
        ('BOTTOMPADDING',(0,0),(-1,-1), 6),
        ('LEFTPADDING',  (0,0),(-1,-1), 8),
        ('BACKGROUND',   (0,2),(-1,2), FILL_CRIT_HDR),
        ('TEXTCOLOR',    (1,2),(1,2),  COL_CRITICAL),
        ('FONTNAME',     (1,2),(1,2),  'Helvetica-Bold'),
        ('BACKGROUND',   (0,6),(-1,6),
            FILL_CRIT_HDR if blocked else FILL_MINOR_HDR),
        ('TEXTCOLOR',    (1,6),(1,6),
            COL_CRITICAL if blocked else COL_MINOR),
        ('FONTNAME',     (1,6),(1,6),  'Helvetica-Bold'),
    ])
    t.setStyle(ts)
    story.append(t)
    story.append(Spacer(1, 8*mm))
    return story


# ── Violation Card ─────────────────────────────────────────────────────────────
def violation_card(v, sty):
    """
    Each violation = a card: header bar + 2-column body.
    Left  (82mm): meta info (ID, type, layer, rule, severity, citation)
    Right (82mm): Description bullets + Suggestion bullets
    """
    sev = v.get('severity', 'Major')
    hdr_fill, body_fill, sev_col = sev_bg(sev)
    ll = v.get('relevantLesson') or {}

    # ── Header row ──
    hdr_left  = f"{v.get('violationId','—')}   |   {v.get('rule_id','—')}"
    hdr_right = sev
    hdr_data  = [
        [Paragraph(hdr_left,  ParagraphStyle('hl', fontName='Helvetica-Bold',
                   fontSize=9, textColor=DARK, leading=11)),
         Paragraph(hdr_right, ParagraphStyle('hr', fontName='Helvetica-Bold',
                   fontSize=10, textColor=sev_col, leading=11,
                   alignment=1))],
    ]
    hdr_tbl = Table(hdr_data, colWidths=[120*mm, 50*mm])
    hdr_tbl.setStyle(TableStyle([
        ('BACKGROUND',   (0,0),(-1,-1), hdr_fill),
        ('TOPPADDING',   (0,0),(-1,-1), 5),
        ('BOTTOMPADDING',(0,0),(-1,-1), 5),
        ('LEFTPADDING',  (0,0),(-1,-1), 8),
        ('RIGHTPADDING', (0,0),(-1,-1), 8),
        ('BOX',          (0,0),(-1,-1), 0.5, colors.HexColor('#BFC9CA')),
    ]))

    # ── Left meta column ──
    meta_lines = [
        Paragraph("Entity Type", sty['card_meta_label']),
        Paragraph(v.get('entity_type','—'), sty['card_meta_val']),
        Spacer(1, 2*mm),
        Paragraph("Layer", sty['card_meta_label']),
        Paragraph(v.get('layer','—'), sty['card_meta_val']),
        Spacer(1, 2*mm),
        Paragraph("Standard", sty['card_meta_label']),
        Paragraph(trunc(v.get('standardCitation','—'), 30), sty['card_meta_val']),
        Spacer(1, 2*mm),
        Paragraph("Confidence", sty['card_meta_label']),
        Paragraph(f"{v.get('confidenceScore',0):.0%}  {'(ML)' if v.get('mlFlagged') else '(Rule)'}",
                  sty['card_meta_val']),
    ]
    if ll.get('violationId'):
        meta_lines += [
            Spacer(1, 2*mm),
            Paragraph("Related Lesson", sty['card_meta_label']),
            Paragraph(trunc(ll.get('violationId','—'), 20), sty['card_meta_val']),
        ]

    # ── Right content column ──
    desc_bullets = to_bullets(v.get('violation_description',''), max_chars=75)
    sugg_bullets = to_bullets(v.get('llmSuggestion','(pending)'), max_chars=75)

    right_lines  = [Paragraph("Description", sty['bullet_label'])]
    for b in desc_bullets:
        right_lines.append(Paragraph(f"\u2022  {b}", sty['bullet']))
    right_lines  += [Spacer(1, 3*mm), Paragraph("Suggestion", sty['bullet_label'])]
    for b in sugg_bullets:
        right_lines.append(Paragraph(f"\u2022  {b}", sty['bullet']))

    # ── Body table: 2 columns ──
    body_data = [[meta_lines, right_lines]]
    body_tbl  = Table(body_data, colWidths=[62*mm, 108*mm])
    body_tbl.setStyle(TableStyle([
        ('BACKGROUND',   (0,0),(-1,-1), body_fill),
        ('VALIGN',       (0,0),(-1,-1), 'TOP'),
        ('TOPPADDING',   (0,0),(-1,-1), 7),
        ('BOTTOMPADDING',(0,0),(-1,-1), 7),
        ('LEFTPADDING',  (0,0),(-1,-1), 8),
        ('RIGHTPADDING', (0,0),(-1,-1), 8),
        ('LINEBELOW',    (0,0),(-1,-1), 0.5, colors.HexColor('#BFC9CA')),
        ('LINEBEFORE',   (1,0),(1,-1), 0.5, colors.HexColor('#D5D8DC')),
        ('BOX',          (0,0),(-1,-1), 0.5, colors.HexColor('#BFC9CA')),
    ]))

    # Wrap in KeepTogether so card doesn't split across pages
    return KeepTogether([hdr_tbl, body_tbl, Spacer(1, 4*mm)])


# ── Section of violations ──────────────────────────────────────────────────────
def violation_section(violations, title, sty):
    if not violations:
        return []
    story = [
        Spacer(1, 3*mm),
        Paragraph(title, sty['section']),
        HRFlowable(width="100%", thickness=0.6, color=VARROC_BLUE),
        Spacer(1, 4*mm),
    ]
    for v in violations:
        story.append(violation_card(v, sty))
    return story


# ── Full detail index table ────────────────────────────────────────────────────
def detail_index(violations, sty):
    story = [
        PageBreak(),
        Paragraph("Violation Index", sty['section']),
        HRFlowable(width="100%", thickness=0.6, color=VARROC_BLUE),
        Spacer(1, 3*mm),
    ]
    headers = ["Violation ID", "Rule", "Severity", "Confidence", "ML?", "Blocks Sign-Off"]
    widths  = [48*mm, 38*mm, 22*mm, 22*mm, 14*mm, 30*mm]
    rows    = [headers]
    for v in violations:
        sev = v.get('severity','')
        _, _, sev_c = sev_bg(sev)
        rows.append([
            trunc(v.get('violationId','—'), 28),
            trunc(v.get('rule_id','—'), 22),
            sev,
            f"{v.get('confidenceScore',0):.0%}",
            "Yes" if v.get('mlFlagged') else "No",
            "YES" if v.get('blocksSignOff') else "No",
        ])
    t = Table(rows, colWidths=widths, repeatRows=1)
    ts = [
        ('BACKGROUND',   (0,0),(-1,0), FILL_HDR_TBL),
        ('TEXTCOLOR',    (0,0),(-1,0), WHITE),
        ('FONTNAME',     (0,0),(-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',     (0,0),(-1,-1), 8.5),
        ('GRID',         (0,0),(-1,-1), 0.3, colors.HexColor('#BFC9CA')),
        ('ROWBACKGROUND',(0,1),(-1,-1), [WHITE, FILL_ALT]),
        ('TOPPADDING',   (0,0),(-1,-1), 5),
        ('BOTTOMPADDING',(0,0),(-1,-1), 5),
        ('LEFTPADDING',  (0,0),(-1,-1), 7),
        ('VALIGN',       (0,0),(-1,-1), 'MIDDLE'),
    ]
    for i, v in enumerate(violations, start=1):
        _, bg, sev_c = sev_bg(v.get('severity',''))
        ts.append(('BACKGROUND', (0,i),(-1,i), bg))
        ts.append(('TEXTCOLOR',  (2,i),(2,i), sev_c))
        ts.append(('FONTNAME',   (2,i),(2,i), 'Helvetica-Bold'))
        if v.get('blocksSignOff'):
            ts.append(('TEXTCOLOR', (5,i),(5,i), COL_CRITICAL))
            ts.append(('FONTNAME',  (5,i),(5,i), 'Helvetica-Bold'))
    t.setStyle(TableStyle(ts))
    story.append(t)
    return story


# ── Main ──────────────────────────────────────────────────────────────────────
def generate_pdf(data: dict, output_path: str = None) -> bytes:
    buf  = io.BytesIO()
    sty  = S()
    doc  = VarrocDoc(buf, meta=data)

    all_v    = data.get('violations', [])
    critical = [v for v in all_v if v.get('severity') == 'Critical']
    major    = [v for v in all_v if v.get('severity') == 'Major']
    minor    = [v for v in all_v if v.get('severity') == 'Minor']

    story  = cover(data, sty)
    story += exec_summary(data, sty)
    story += violation_section(critical, f"Critical Issues  ({len(critical)})", sty)
    story += violation_section(major,    f"Major Issues  ({len(major)})", sty)
    story += violation_section(minor,    f"Minor Issues  ({len(minor)})", sty)
    story += detail_index(all_v, sty)

    doc.build(story)
    pdf_bytes = buf.getvalue()

    if output_path:
        with open(output_path, 'wb') as f:
            f.write(pdf_bytes)
        print(f"[pdf_generator] Saved -> {output_path}")

    return pdf_bytes


# ── CLI ──────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    sample = os.path.join(os.path.dirname(__file__), '..', 'data', 'sample_violations.json')
    with open(sample) as f:
        data = json.load(f)
    out = os.path.join(os.path.dirname(__file__), '..', '..', 'sample_report.pdf')
    generate_pdf(data, output_path=out)
    print(f"Report -> {os.path.abspath(out)}")
